CREATE TYPE "public"."book_category" AS ENUM('adventures', 'comedy', 'comics');--> statement-breakpoint
CREATE TYPE "public"."book_image_kind" AS ENUM('cover', 'preview');--> statement-breakpoint
CREATE TYPE "public"."book_link_vendor" AS ENUM('amazon', 'goodreads', 'internal');--> statement-breakpoint
CREATE TYPE "public"."book_status" AS ENUM('published', 'preorder', 'upcoming');--> statement-breakpoint
CREATE TABLE "book_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "book_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" text NOT NULL,
	"kind" "book_image_kind" NOT NULL,
	"src" text NOT NULL,
	"alt" text NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "book_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "book_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" text NOT NULL,
	"vendor" "book_link_vendor" NOT NULL,
	"url" text NOT NULL,
	"label" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "book_reviews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "book_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"review" text NOT NULL,
	"stars" integer NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "books" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"subtitle" text,
	"status" "book_status" NOT NULL,
	"category" "book_category" NOT NULL,
	"release_date" timestamp,
	"featured" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"short_description" text NOT NULL,
	"long_description" jsonb NOT NULL,
	"content_warnings" jsonb,
	"availability" text NOT NULL,
	"isbn" text,
	"page_count" integer,
	"series_name" text,
	"series_book" integer,
	"series_total" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "books_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "book_images" ADD CONSTRAINT "book_images_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_links" ADD CONSTRAINT "book_links_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_reviews" ADD CONSTRAINT "book_reviews_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;