CREATE TABLE "nav_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nav_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" text NOT NULL,
	"href" text NOT NULL,
	"section" text DEFAULT 'main' NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"external" boolean DEFAULT false NOT NULL,
	"description" text,
	"visible" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "site_settings" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"name" text NOT NULL,
	"tagline" text NOT NULL,
	"canonical_url" text NOT NULL,
	"og_image" text NOT NULL,
	"footer" text NOT NULL,
	"socials" jsonb NOT NULL,
	"contact" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "nav_section" text;